spring.application.name=debug-service
spring.config.import=file:../.env[.properties], file:../.eurekaclient.env[.properties]
server.port=${custom.parameters.server.debug.port}
server.servlet.context-path=/${custom.parameters.server.debug.host}