spring.application.name=api-gateway
spring.config.import=file:../.env[.properties], file:../.eurekaclient.env[.properties], file:../.db.env[.properties]
server.port=${custom.parameters.server.gateway.port}

spring.datasource.url=jdbc:mysql://${db.host}:${db.port}/${db.database_name}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=${db.driver_class}
spring.jpa.hibernate.ddl-auto=update


spring.cloud.gateway.server.webmvc.routes[0].id=facebook
spring.cloud.gateway.server.webmvc.routes[0].uri=https://www.facebook.com/
spring.cloud.gateway.server.webmvc.routes[0].predicates=Path=/facebook/*
spring.cloud.gateway.server.webmvc.routes[1].id=google
spring.cloud.gateway.server.webmvc.routes[1].uri=https://www.google.com/
spring.cloud.gateway.server.webmvc.routes[1].predicates=Path=/google/*
spring.cloud.gateway.server.webmvc.routes[1].filters=StripPrefix=1
spring.cloud.gateway.server.webmvc.routes[2].id=debug-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://debug-service
spring.cloud.gateway.server.webmvc.routes[2].predicates=Path=/${custom.parameters.server.debug.host}/*
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://base64
spring.cloud.gateway.server.webmvc.routes[3].predicates=Path=/${custom.parameters.server.module.base64.host}/*
