spring.application.name=user
spring.config.import=file:../.env[.properties], file:../.eurekaclient.env[.properties], file:../.module.env[.properties], file:../.db.env[.properties]

logging.level.com.cyberSAKura=DEBUG